import type { Action } from "@prisma/client";

export const mapActionToShares: Record<Action, number> = {
  USER_SHOP_NEW: 10,
  USER_SHOP_UPDATE: 5,
  USER_REFERRAL_CREATER: 100,
  USER_REFERRAL_RECEIVER: 1,
  USER_CHOCOLATINE_CRITERIAS_REVIEW: 100,
  USER_CHOCOLATINE_COMMENT_SCORE: 50,
  USER_LINKEDIN_LIKE: 10,
  USER_LINKEDIN_COMMENT: 20,
  USER_LINKEDIN_SHARE: 30,
  USER_LINKEDIN_POST: 50,
  USER_LINKEDIN_FOLLOW_PAGE: 5,
  INVESTOR_EURO_AMOUNT: 1,
  BUILDER_HOUR_AMOUNT: 1,
  FEEDBACK: 50,
};
